### ISSUE TITLE
problem with "paste" in config   

### ISSUE THREAD

**Issue by ekate** [NYULibraries/primo-endpoint#11]
For a new collection I need to paste several fields and strings to create a url as "available" field in primo. 
available:
        paste:
          - "http://dlib.nyu.edu/findingaids/html/fales/mss_496/dsc" 
          - ref_ssi
          - ".html"
 The url is not constructed, e.g. the value of "available" field is empty. If I use ".html#" all works as expected. I think html is interpreted as variable name. Is it possible ? Could you please take a look. I add the branch called mss_496 which has a new config

**Comment by dylex** [comment]
That sounds right -- if there are only alphanumerics or `"._"` it's treated as a field name. If you change it to `- string: ".html"` does that work?

**Comment by dylex** [comment]
I think you could also write it all as `"http://dlib.nyu.edu/findingaids/html/fales/mss_496/dsc/${ref_ssi}.html"` if that helps.

**Comment by ekate** [comment]
Ah, okay. That work. Thanks
