### ISSUE TITLE
Startup script for  primo-endpoint

### ISSUE THREAD

**Issue by ekate** [NYULibraries/primo-endpoint#7]
we need a script which can start and stop the service on CENTOS-7

**Comment by dylex** [comment]
Would you have a preference between:

- binary rpm with some way to build it that requires existing stack/haskell install
- buildable self-contained dockerfile that installs stack and builds everything

**Comment by ekate** [comment]
dockerfile is fine

**Comment by dylex** [comment]
Has now been containerized and builds and runs completely in docker from a bare git checkout.
